# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: tcpproxy

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: tcpproxy
    main: ./cmd/tcpproxy
    binary: tcpproxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "ghcr.io/myhops/tcpproxy:{{ .Tag }}"
      - "ghcr.io/myhops/tcpproxy:v{{ .Major }}"
      - "ghcr.io/myhops/tcpproxy:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/myhops/tcpproxy:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

release:
  github:
    owner: myhops
    name: tcpproxy
  draft: false
  prerelease: auto
